# SwiftLint Configuration for ONVY Health SDK
# Enforces Swift style guidelines and best practices

# Disabled Rules
disabled_rules:
  - trailing_whitespace  # Handled by formatter

# Opt-in Rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_assert
  - discouraged_optional_boolean
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - force_unwrapping
  - function_default_parameter_at_end
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Rule Configurations
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 100
  error: 200

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 400
  error: 600

file_length:
  warning: 500
  error: 1000

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level: 2
  function_level: 3

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 60
    error: 80
  excluded:
    - id
    - x
    - y
    - z

type_name:
  min_length: 3
  max_length: 60

# Excluded paths
excluded:
  - Pods
  - .build
  - DerivedData
  - Carthage
  - fastlane/report.xml
  - fastlane/Preview.html
  - fastlane/screenshots
  - fastlane/test_output

# Custom rules
custom_rules:
  # Enforce documentation for public APIs
  public_api_documentation:
    name: "Public API Documentation"
    regex: '^(public|open)\s+(func|var|let|class|struct|enum|protocol)\s+(\w+)'
    message: "Public APIs should be documented"
    severity: warning
    match_kinds:
      - keyword
      - identifier

  # Discourage force unwrapping
  force_unwrapping_discouraged:
    name: "Force Unwrapping Discouraged"
    regex: '!\s*[^=]'
    message: "Avoid force unwrapping. Use optional binding or guard statements instead."
    severity: warning

# Reporter
reporter: "xcode"
